### ISSUE TITLE
Don't assign/use real slots during speculative execution

### ISSUE THREAD

**Issue by dstockwell** [PolymerLabs/arcs#139]
Probably by not passing SlotManger to Arcs used for speculative execution.

**Comment by dstockwell** [comment]
Although @shans thinks it might already work this way.

**Comment by shans** [comment]
It does (or at least used to) in the tests. If you look at test/demo-flow-test.js you can see that a MockSlotManager isn't installed until after speculative execution. At one point, there was *no* slot manager installed before this.

**Comment by dstockwell** [comment]
I was assuming that https://github.com/PolymerLabs/arcs/blob/master/runtime/outer-PEC.js#L54 would need to be modified to not assume that there is a `this.slotManager`?

**Comment by mmandlis** [comment]
Probably it did work earlier, but my previous change broke it, as i pass a SlotManager to the Arc https://github.com/PolymerLabs/arcs/blob/master/runtime/test/demo-flow-test.js#L30

i'm not sure though how it could have worked because outer-PEC always assumes it has slotManager.

Let me try to solve this.

**Comment by shans** [comment]
I think actually it probably didn't work, there was just the server-side slot manager until I overrode it.
