### ISSUE TITLE
App Shell performance investigation

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#1450]
Empirically I have been experiencing high UI latency and jank for at least a few weeks and it seems to be getting worse recently. I've been creating a large number of Arcs for development purposes (~70 tiles right now in my Launcher) which could relate. Filing issue to allow tracking notes and discussion.

At current ToT on my linux workstation, with `index.html`, cache enabled and warm, rough timing:

- Launcher page: ~6.5s to render the Arc tiles
- The Search hover peek in/out (just the one row worth) takes ~0.5s to pop out or pop in, and seems to render just one frame of animation
- Words Arc page: ~7.5s to render the 'Start Game' button top left

@sjmiles @mmandlis

**Comment by sjmiles** [comment]
I think what you are dealing with here is specific pain from Xen sub-template rendering, which is (1) not optimized and (2) being abused a bit by shell. The good news is that the fruit is ... not too high?

In particular, the Tools flyout (Handle Explorer, Xen Explorer) is doing a lot of useless DOM re-generation.

The Launcher also relies on sub-templates, and since you have (relatively) a lot of tiles this is becoming noticeable.

A rough plan: 
1. disable the tools panels completely to get a read on the level of improvement there.
2. add node-reuse to the sub-template renderer.
3. consider different usage pattern for the launcher (each Arc is it's on FB node, so the launcher is populated asynchronously one-Arc at a time).

There are also systemic performance concerns that we should study, I think this can be a separate effort.

**Comment by mykmartin** [comment]
Assigning to @sjmiles since he's actually working on it :)

**Comment by sjmiles** [comment]
There is always more perf work that can be done, but I believe the egregious issues have been resolved: closing.
