### ISSUE TITLE
Some suggestions must be clicked twice to be rendered into a new arc.

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#1519]
To repro:
- visit launcher, become Walt or Berni or some user that has at least one post and one word game in their BOXED_posts data
- type 'post' into text box in hover popup at bottom, choose 'Show post list (2 items)' or similar.
- note you've navigated to a new arc page but the recipe does not execute -- you have to choose the suggestion again from the text box at bottom.

Note that 'write post list' does not seem to suffer from this issue.

@seefeldb @sjmiles @mmandlis

**Comment by sjmiles** [comment]
This is another problem related to the fact that `context` stores (i.e. profile_*, boxed_*, anything that's not explicitly stored in FB) are instantiated asynchronously.

Since these data are dynamic it's a wildly easier model to treat them as streams (that never have a _ready_ point) but there are various tradeoffs. We can use retries today to model streams view (maybe call this _fault tolerance_?) and/or we can pursue blocking arcs work on a _ready_ signal.
