### ISSUE TITLE
Rename Suggestinator to Strategizer

### ISSUE THREAD

**Issue by mmandlis** [PolymerLabs/arcs#168]
or Strateginator? :)
This is to avoid confusion between "suggestions" that currently mean suggested plans and "suggestions" that are currently named "descriptions". After this is done, description-generator should be renamed to suggestions-generator (or suggestinator?) 

Shane, Doug, please, let me know when is a good time to do the renaming to not interfere with any of your work in progress, thanks!

**Comment by dstockwell** [comment]
I was landing the strategizer with the new name, then planning to remove the old suggestinator when it was ready to switch over, but I see how that might get in your way. But it's fine to just rename suggestinator.js to old-suggestinator.js or something. I don't think we need to rename any of the classes since they will just be removed later.

**Comment by mmandlis** [comment]
oops, i seem to have totally missed this - https://github.com/PolymerLabs/arcs/commit/fea7b79ba16a37ae2459ad78dcfaa2028711910e
i guess, i just hold off renaming descriptions to suggestions until the new strategizer replaces the old suggestinator. thanks.
