### ISSUE TITLE
Particle not updating: wrong signalling for muxed item data changes

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#1692]
https://polymerlabs.github.io/arcs-live/shell/apps/web/?serial=&arc=-LIHtapeVBM9zilc4XBJ

Clicking one of the `account` entries (Plaid Savings, Plaid Checking, Plaid Premier Checking, Plaid Credit Card)  in the first list generally displays corresponding `transaction` entries in the second list.

However, when switching selection between `Plaid Savings` and `Plaid Premier Checking` (or vice versa) the second list doesn't update.

Studying the stores, it looks like the data is updating, but the list Particle is not being notified (maybe?).

**Comment by mykmartin** [comment]
Ack; I can see the problem on the arcs-live link, but using a local server I'm not getting the transaction list at all. (Repo is at commit 2a0fe9f5)

**Comment by mykmartin** [comment]
Ok, repro'd locally using the same arc as above.

**Comment by mykmartin** [comment]
And now the live link doesn't show the transaction list. I tried pulling the sjmiles repo locally so I could fiddle with the plaid particles, and changing the import list in shell/apps/common/config.js appears to have affected the live instance.

**Comment by mykmartin** [comment]
I attempted to up-poison the live instance by reverting my local changes, rebuilding and refreshing the locally-served page. Hasn't helped; the live link still won't show transaction lists.

Scott: what user are you operating as for this bug?

**Comment by sjmiles** [comment]
Sorry, I didn't include the instructions for rebuilding the arc. Here are the steps for posterity:

1. search for `plaid`
2. choose 'Show plaid accounts...'
3. search for `plaid`
4. choose 'Show plaid transactions...'
5. Try clicking account entries.

**Comment by sjmiles** [comment]
>> changing the import list in shell/apps/common/config.js appears to have affected the live instance.

This should not be possible. All JS files should flow from `github.io` if you are using arcs-live.

**Comment by shans** [comment]
This issue looks like a problem in render updates, not in notification. If I put a breakpoint on line 73 of List.js  then I see the notification for the new list items come through (and this results in a new model being returned), but that obviously gets lost somewhere between the return statement and rendering.

**Comment by shans** [comment]
Further to this, there are actually render calls being made to PlaidTransactionItem for the items to be rendered, so all the data is getting to the right places. Something in Slot rendering maybe?

**Comment by mmandlis** [comment]
I can reproduce the problem on arcs-live. Will debug now.
But locally I don't get the "show plaid transactions" suggestion, any ideas?

**Comment by mmandlis** [comment]
My theory is that this is happening because the 2 accounts have the same number of transactions (I cannot verify it, because I cannot reproduce locally @sjmiles I need you help here).

When transactions' SelectableList gets renderSlot call with the new model and the new model has the same number of items, when doing the model update xen call, the live dom isn't changed and hence the observer isn't triggered.

**Comment by mmandlis** [comment]
In more detail, the problem happens because when `List` particle is rendered with the same number of items, even though theses are different items, the Observer isn't called https://github.com/PolymerLabs/arcs/blob/master/runtime/slot-dom-consumer.js#L255, and so the `Multiplexer`'s slot containers aren't being updated.

I created this PR to make it easier to reproduce and debug this problem locally https://github.com/PolymerLabs/arcs/pull/1717
