### ISSUE TITLE
Gifts Demo failing firebase-storage version assertion (using runtime storage & serialization)

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#1774]
1. Start launcher with `&serial&store` arguments. 
2. Begin _Gifts Demo_ flow by typing a search term (e.g. `brows`)
3. Choose `Show products from your browsing context...`.
4. Choose `Check shipping ...`

Assertion fails at L327 of `firebase-storage.ts` because `data.version > this.version` resolves to `0 > 1`.

Reproduced via arcs-live, should repro from any user (I used `Cletus`).

Previous issues have arisen because of app-shell interference, so I will keep looking from that angle. Setting `store` does look to be defeating the storage shim, as intended.

**Comment by sjmiles** [comment]
Side note, it's generally helpful if assertions like this describe themselves (via the second parameter to `assert`).

**Comment by lindner** [comment]
I notice that `version` isn't a declared member of the class.

**Comment by shans** [comment]
version is in the superclass chain.

This is super weird; firebase is sending a {version: 0} message, but as far as I can tell this is a newly constructed location, so that shouldn't be happening. We're not sending any commits to firebase before the assert, either.

I wish Doug was around to look into this :(

**Comment by lindner** [comment]
also fails at d1a0360db37190906066f50e9bd6b201444492da

bisecting

**Comment by sjmiles** [comment]
Thanks for the help!
