### ISSUE TITLE
Shape.handlesMatch returns non-boolean

### ISSUE THREAD

**Issue by lindner** [PolymerLabs/arcs#1798]
See: 

https://github.com/PolymerLabs/arcs/blob/1e58cc301dde2ddcc28d9f30d13ea4da381e0e43/runtime/ts/shape.ts#L328

The following return value is not a boolean.  Can someone with more knowledge of this history advise? 

```
   if (left.isVariable) {
      return [{var: left, value: right, direction: shapeHandle.direction}];
    } else {
       ...
    }
```

The code in question is called later on like this:

```
    const handleMatches = this.handles.map(
      handle => particleSpec.connections.map(connection => ({match: connection, result: Shape.handlesMatch(handle, connection)}))
                                      .filter(a => a.result !== false));
```

This is effectively evaluating to true.

**Comment by lindner** [comment]
Can someone have a look at this inconsistency?

**Comment by cromwellian** [comment]
This seems like a straight up bug?

**Comment by shaper** [comment]
Pinging for status update as this is marked P1.

**Comment by mmandlis** [comment]
@shans if you don't have time to work on this, i could take over (once I get back)

**Comment by shaper** [comment]
I just read the code (it's now in `interface-info.ts`) and two notes:

1. `handlesMatch` now has types specified as:
`  static handlesMatch(interfaceHandle, particleHandle): boolean|{var, value, direction}[] {`

2. I think @shans probably wrote this code intentionally, relying on the fact that if the left is a `TypeVariable` it returns `[{var, value, direction}]` which is `!== false`, with the intent of using the returned info for other purposes in the future.

So I'm going to close this issue as it's not clear there is more work to do (the original cause for opening it was when there were no types specified for the method at all). The code could be cleaner since today it's only checking for a boolean, but I'm guessing Shane had plans, and it's only used within `interface-info.ts` statically anyway, so it's basically an implementation detail that doesn't leak.

Feel free to reopen or comment further as needed.
