### ISSUE TITLE
Issues with dynamic descriptions with explicit template/model.

### ISSUE THREAD

**Issue by piotrswigon** [PolymerLabs/arcs#1965]
I have a case where `setParticleDescription(string)` works, but `setParticleDescription({template, model})` does not. I will be landing a patch with a comment about this in artifacts/Music/source/FindShows.js.

Something to investigate when we have some more bandwidth.

**Comment by mmandlis** [comment]
from https://github.com/PolymerLabs/arcs/pull/1966#issuecomment-424244628:
Long time since this was tested, but the syntax is:
https://github.com/PolymerLabs/arcs/pull/563/files#diff-47799113e5d96f11ad1720ff985b68bcR166
the template should be an html with xen-like templating.
Another example is in the description tests: https://github.com/PolymerLabs/arcs/blob/master/runtime/test/description-test.js#L820

**Comment by mmandlis** [comment]
fixed with https://github.com/PolymerLabs/arcs/pull/2041
