### ISSUE TITLE
Pathological slow downs caused by backingStores 

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#2307]
I believe this is a well known problem, but I wanted to have a tracking ticket. Please add detail as desired.

**Comment by shaper** [comment]
@shans do you need more detail or repro steps? Do we know what set of work we expect to address this? I remember some discussion from SEA but would like to not illustrate my potentially poor recollection abilities.

**Comment by shans** [comment]
The problem comes from two sources:

(1) the storage engine is inefficient when it comes to large backing stores. This is something that we need to address at some point (e.g. by not loading backing store contents locally). I had hoped to address it as part of technical debt but I don't think that we'll manage to do that this year.

We could look at a more targeted fix for this; I think there's a reasonable chance it wouldn't be too difficult (but there's also a chance that it will be really hard...)

(2) we don't do any entity re-use at the moment. e.g. the IDs for searched TV shows are always freshly generated; user entities are always given new IDs; etc. This is a design problem (I think) - ideally we'd have stable ids for entities which are stable but the system doesn't really let us do that as it stands.

We really need to fix this too, but I am not sure what the best approach is.

**Comment by sjmiles** [comment]
Thanks @shans. 

When we generalized user-arc lists into Stores, this problem became a bit more of a day-to-day problem. Because the Arc meta data is now kept in `backingStores`, throwing away that database node leaves user launchers in broken states. 

The new recourse is just throwing away the entire database, which is painful.

The slowdown is happening again now (1/22/2019). You should be able to repro by invoking Find Restaurant. The list can take a long time to render, and selecting a restaurant can take several seconds.

Maybe we can look for the _targeted fix_ you mentioned, maybe just for the _green box_?

**Comment by shaper** [comment]
@lindner is going to follow up here to let us know whether this issue (slowdown with backingStores as they accumulate) is easy to repro and/or otherwise observable in Pouch. This may require looking at https://github.com/PolymerLabs/arcs/issues/2605 first.
