### ISSUE TITLE
Cannot deserialize RestaurantsDemo

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#2313]
Steps to repro (hopefully):

1. load `shell_0_6_0/web-shell`
1. type 'restaurants' into search box
1. choose `[demo] find restaurants ...`
1. refresh

![image](https://user-images.githubusercontent.com/98045/49050226-37017c00-f197-11e8-86c9-f4206d20e1f8.png)

**Comment by piotrswigon** [comment]
I will take it over.

**Comment by piotrswigon** [comment]
The root cause is that we inherit the session from the previous instance of the arc and get conflicts in IDs. Local ID starts again at 0 and when newly generated 'session:arc_id:local_id' overlaps with already existing ID we mess up when operating on the recipe (cloning in particular).

Patch with a fix coming soon.

**Comment by sjmiles** [comment]
Thanks for the updates @piotrswigon.
