### ISSUE TITLE
manifest parser confused by comment after resource-start array

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#2467]
Parses succeeds:
```
import '../Pipes/PipeEntity.schema'

resource PipeEntityResource
  start
  //[{"type": "tv_show", "name": "star trek"}]
  [{"type": "artist", "name": "in this moment"}]

store ExamplePipeEntity of PipeEntity 'ExamplePipeEntity' @0 in PipeEntityResource
```

Parser fails:
```
import '../Pipes/PipeEntity.schema'

resource PipeEntityResource
  start
  [{"type": "artist", "name": "in this moment"}]
  //[{"type": "tv_show", "name": "star trek"}]

store ExamplePipeEntity of PipeEntity 'ExamplePipeEntity' @0 in PipeEntityResource
```

Error content:
```
Error parsing JSON from 'PipeEntityResource' (Unexpected token / in JSON at position 47)'
  store ExamplePipeEntity of PipeEntity 'ExamplePipeEntity' @0 in PipeEntityResource
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Difference is only the order of the two lines after `start`.

**Comment by sjmiles** [comment]
@Cypher1 Thanks for working on the repro. I added some notes (to #2498) about additional requirements to produce the failure (upshot: the problematic import must itself be transitively imported).

**Comment by Cypher1** [comment]
So, I haven't had a deep look at this, but it seems to me that the error is coming from the JSON parser, not the manifest parser.
The `position 47` is the start of the comment in the JSON resource.

This makes me wonder why the previous comment was accepted (the manifest parser will pass the comments through to the JSON parser used for resources.

```JSON.parse('  [{"type": "artist", "name": "in this moment"}]//[{"type": "tv_show", "name": "star trek"}]')``` fails with the error you reported, but so does
```JSON.parse('//[{"type": "tv_show", "name": "star trek"}][{"type": "artist", "name": "in this moment"}]');```.

Turns out that the `ResourceStart` parser (the one holding the 'start' keyword) is defined with a eolWhiteSpace following it. This eats white space (and comments) until the next non-whitespace character.

So, the way I see it, either we can disable the start keywords support for comments or we can look into a JSON parser that supports comments.

@shans to advise?

**Comment by sjmiles** [comment]
Ok, so this was straight up user-error, which is to say I provided malformed JSON.

This makes sense, and it says "JSON parser" right there in the error message!

Thanks for tracking this down.

**Comment by sjmiles** [comment]
Maybe it's possible to echo the actual bad JSON at this point, that could help folks recognize the mistake.

**Comment by Cypher1** [comment]
Working on something else right now but should be able to make this patch before end of work day.
Also want to try to ensure that the successful case you presented isn't accepted either as I believe it is a 'developer weirdness' issue. I still want to support 'start // comment about resource' in some form though.

Talking to @shans briefly it may be alright to allow.

**Comment by Cypher1** [comment]
@sjmiles Have something of a fix for this (https://github.com/PolymerLabs/arcs/pull/3033) but haven't changed the error message, only made it show up more consistently when after a 'start' Resource section. I decided against printing the json as the error already shows which source the error came from and the json could be very large, making other errors harder to spot.

Happy to discuss further but will close this if the PR is accepted.

**Comment by sjmiles** [comment]
Ok, I trust your judgement. One last bit:
```
Error parsing JSON from 'PipeEntityResource' (Unexpected token / in JSON at position 47)'
  store ExamplePipeEntity of PipeEntity 'ExamplePipeEntity' @0 in PipeEntityResource
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Note that the line with the carets is generally supposed contain the offending tokens, and specifically there are 47 carets to point to the exact error. However, that line is not the actual offender (the offending code is not visible here) and the 47 carets is just wrong.

I'm not advocating for any particular solution at this point, but this message is potentially misleading.

**Comment by Cypher1** [comment]
Thanks Scott, I do appreciate that.

About the error message, sorry to ask for this, but can you open a PR with a failing test showing the error you're describing? I think one of my next tasks will be to add explicit parse errors (rather than relying on the back tracking mechanism running out of options) but I need to get slandles to a usable state first.

**Comment by Cypher1** [comment]
I think for now this can be closed, if you hit it again feel free to open it again.
