### ISSUE TITLE
Consider refactoring "suggestion composer > suggestion set-slots" test

### ISSUE THREAD

**Issue by piotrswigon** [PolymerLabs/arcs#2523]
`Suggestion composer: suggestion set-slots` is building outer arc suggestions connecting to the inner arc particles. This used to work when inner arc was instantiated inside the outer arc. As inner arcs are properly represented as their own Arc instance (#2524), this test no longer works.

@mmandlis could you take a look at it? Alternatively you can explain what exactly needs to be tested and I can take a look.

PTAL here is the arc graph, it shows that the LightCandles particle gets attached to one of the MakeCake particles (which is multiplexed). MakeCake particles now live in the inner arc, so the test fails as LightCandles cannot resolve against the outer arc anymore.

![screen shot 2018-12-31 at 9 14 15 am](https://user-images.githubusercontent.com/26159485/50619380-0d353500-0f4d-11e9-9a87-39b72ad2935f.png)

**Comment by mmandlis** [comment]
This isn't suggestion-composer refactoring - the problem is not an inline suggestion not being rendered, but the suggestion isn't produced in the first place.

Inner arcs implementation in https://github.com/PolymerLabs/arcs/pull/2524 introduces a regression in the sense that we no longer strategize for the contexts of the inner arcs - like we incidentally did before, and want to explicitly do with proper inner arcs as well.

**Comment by piotrswigon** [comment]
> we no longer strategize for the contexts of the inner arcs - like we incidentally did before, and want to explicitly do with proper inner arcs as well.

Yes - Just confirming that our understanding here is the same.

**Comment by piotrswigon** [comment]
Sorry for misleading title. `suggestion composer`: `suggestion set-slots` was intended as a name of a test. As in "Consider how to refactor this test, so that it still tests what it should test, without relying on inner arc strategization".
