### ISSUE TITLE
Strategy-explorer not showing suggestions for the `-null` arc

### ISSUE THREAD

**Issue by mmandlis** [PolymerLabs/arcs#2546]
This happens because recipe-index generates plans that override the suggestions produced by Planner.
I think recipe-index is repeatedly re-triggered by `ArcsRecipeEditor::runPlanner()`.

**Comment by piotrswigon** [comment]
It turns out there were 2 separate issues. 1) as observed, recipe editor was sending strategization, which it shouldn't. 2) is that Index strategization was sent *after* the strategization of the already serialized suggestions, and the former was overriding the latter. Sent a fix to both in #2551.

Thanks for reporting. Sorry for bugs.
