### ISSUE TITLE
Implement Arcs Repos

### ISSUE THREAD

**Issue by lindner** [PolymerLabs/arcs#2810]
As part of the ingest design it's become clear that we need to have a well-documented and consistent structure for on-disk artifacts when running Arcs in a server environment.

The pain points come from:
- Current server is in-memory and everything goes away on restart. (Makes testing hard)
- On disk support is available in cloud deployment, but it is not being tested.
- We need to really think about versioning and how the system as a whole can work well with new versions  of Runtime.

To that end I propose that we support an on-disk format for the Arcs Repo, and a set of commands to manage it.  To make things easy for developers and administrators we should consider mimicing existing repo systems like git.

The on disk repo would be documented, but it might look something like this:

```
   .arcs/
      config.json
          {"version": 1,
            ...
          }
      db/pouchdb-v1/
           ....dbs....
      db/otherdb-v1
           ....dbs....
      logs/
      tmp/
```

To work with repos a set of command line tools would be available
- `arcs init` would initialize a repo
- Other `arcs` commands would use the default repo when running node tools.  This would allow for on-disk persistence.
- The Arcs PouchDb would automatically store it's data inside the repo.  To start the server you would run `arcs serve`

## Version Changes

As we expect the repo format to change over time it's important to start out with versions.  For simple upgrades the version upgrade could be done automatically.  For more complex cases a separate upgrade tool may be necessary.

## Config

In an ideal world configuration data would be stored directly in the Arcs storage system.  In practice that may not be viable.  At minimum the `version` needs to be made available.  There may need to be private references to keys that should remain outside arcs itselft.  There are also use cases like the default port for the server and other tidbits also feels out of scope.

## Security Features, Logs, etc.

Repos, when initialized can have private keys and other security features baked in.  We could even include a default user with a public/private key.

Each Repo could also announce it's key using a Certificate Transparency mechanism.

A Repo can have an associated Audit database that can store specific usages of the repo.  The Audit DB.

**Comment by lindner** [comment]
Also would like feedback on this; @cromwellian would you want to start?.  It obviously depends on the proposed CLI in #2802

**Comment by cromwellian** [comment]
In the current GCP cloud management system, part of this configuration information resides in GCP/Kubernetes metadata.  I suggest we take a look at Kubernetes ConfigMaps (https://cloud.google.com/kubernetes-engine/docs/concepts/configmap) and try to rationalize the config.json to match that. 

The reason we may want to do this is because the disk storage system might live separately from the configuration information. For example, one or more encrypted disk volumes might have to be attached. If the config information can be read and replicated into GCP/Kube, and this configuration information contains necessary public key/key fingerprint data needed for remounting the disk, then this will be advantageous. 

Consider the instance where the NodeVM isn't running.

1) Take DeviceKey from client. Spin up or obtain from a pool, a NodeVM. 
2) Read Config based on DeviceKey from GCP/Kube ConfigMaps
3) Get Public Key and ask Client to send wrapped disk decryption Key
4) Mount Arcs Repo encrypted disk
5) Now pouch can read db/pouch-db/...

So I'm not suggesting that we change the format your proposed, since obviously we want local development to work, as well as non-Kubernetes deployments to work. However, if we make sure the repository configuration can be replicated and stored in your cluster management system (e.g. Kubernetes), then the system can still have the information needed to mount the right storage systems without needing a persistent disk attached to do so. 

Ideally, we want the nodevms to be ephemeral and diskless, and only attach the physical disk repo (encrypted) when needed.

**Comment by lindner** [comment]
Closing for now.  Can possibly be revived once storage is in scope and cloud based systems are refocused.
