### ISSUE TITLE
Manifest parser allergic to prefix `slot`, error message unclear

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#2961]
Example, this recipe:
```
schema Sloturnicus
  Text foo

particle P in './p.js'
  in Sloturnicus s
```

I get:

```
Parse error in 'manifest.manifest' line 5.
Expected "alias", "import", "meta", "particle", "recipe", "resource", "schema", "store", a particle item, an annotation (e.g. @foo), or an interface but "i" found.
    in Sloturnicus s
    ^
```

`Sloturnicus` is actually causing the failure (because it starts with `slot`) and not `in` as reported.

**Comment by Cypher1** [comment]
Working on this, having some trouble seeing how this is possible but have added a test verifying the behavior and ensuring that once it is landed we don't regress.

**Comment by Cypher1** [comment]
For the record, the problem was that the UpperIdent and SlotType parsers overlapped and the SlotType parser also didn't ensure that there was whitespace following the 'Slot' keyword.
I've updated the parser to require, but not consume whitespace after the 'Slot' keyword. Ideally we would also handle eof so that the SlotType can be used in any context, but we don't currently allow this and so it should be fine.

I would prefer to have a cleaner approach, e.g. separating the space of keywords and identifiers.
