### ISSUE TITLE
Typing Global Objects? 

### ISSUE THREAD

**Issue by alxrsngrtn** [PolymerLabs/arcs#3062]
Sometimes we need to use properties on global objects that haven't been typed for access. For instance, we may import a module dynamically, and then want to access it as a property off of window. 

```
  /* tfjs is loaded dynamically here */
  // ...
  return window.tf; // will cause a typescript error
```

In cases like these, should we prefer [Global Augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#global-augmentation) or avoid the typing situation (like the following)?

```
  return window['tf'];
```

**Comment by alxrsngrtn** [comment]
This issue [came up](https://github.com/PolymerLabs/arcs/pull/3052#discussion_r286249626) a few types in a recent PR,.

**Comment by lindner** [comment]
One way to get around this is to cast to the desired type.

return window['tf'] as TensorFlowThingie;

**Comment by sjmiles** [comment]
I think this is possibly a bad example. The only reason `tf` ends up on Window (or used to) was because it was dictated by the `tfjs` code itself. 

Today, this detail is hidden in `platform/tf-web.ts`. That module exports and async function called `requireTf` which returns the needed reference. The use of `window` is encapsulated as an implementation detail.

**Comment by shaper** [comment]
Appears resolved in earlier discussion, reopen if further.
