### ISSUE TITLE
Accessing Entity.id when a Schema publishes it's own id field

### ISSUE THREAD

**Issue by sjmiles** [PolymerLabs/arcs#3147]
Particles that generate set-slots for multiplexer are required to use Entity::id's to map multiplexed slots against source source data (aka `subid`).

Sometimes the Entity::id getter is hidden by the Entity data itself publishing an id getter.

I've worked around this in List particles with the following (grotesque?) code:
```
    getId(entity) {
      return Object.getOwnPropertyDescriptor(entity.__proto__.__proto__, 'id').get.apply(entity);
    }
```
See also #1574 and #581.

**Comment by mykmartin** [comment]
Turns out this is a broader problem; we have several fields and member methods on EntityClass that can be shadowed by the schema. The plan is to change it up so the object handed to particles is the plain JS Proxy itself (or possibly a very thinly wrapped one), and we provide static lookups on Entity to access arcs-specific data.

Particles can still use entities with schema-based fields in the usual sense: `e.address`, and access to the "system-level" fields would be `Entity.getId(e)`.

**Comment by sjmiles** [comment]
This has been fixed.
