### ISSUE TITLE
Short-term unification of slots and handles for the SDK

### ISSUE THREAD

**Issue by piotrswigon** [PolymerLabs/arcs#3664]
## Problem

We’re telling the “slandels” story in our documentation. The story is that slots are stored in handles, but it’s not fully true yet (slandels v2 will bring it fully I believe), and the recipe syntax in particular lags behind. This brings mental friction to makes it hard to explain our concepts.

## Goal

Make minimal agreeable change to the recipe syntax that unifies slots and handles to the extent feasible.

### Particle Spec connection syntax is different between handles and slots.
`consume root` vs `in Thing {Text value} thing`

I believe what you already have in mind would be a good unification: `consume Slot root`

### Recipe connection syntax is different between handles and slots.
`provide connection as localName` vs `connection -> localName`

Suggestion is to consider: `connection provides localName` / `connection consumes localName`

### Declaration of slots vs handles is different.
`slot 'rootslotid-root' as root` vs `map/create/copy 'BOXED_arcs' as shared`

I (@piotrswigon) am reasonably convinced right now that slots should be _mapped_ into the arc, so ideally I would like to see `slot 'rootslotid-root' as root` changed into `map 'rootslotid-root' as root`. This may involve making some changes in the resolution process - to be investigated.

I'll soon write a one pager arguing why I believe slots should be mapped.

## Execution Notes

This task involves:

1. Generating a minimal proposal and effectively championing it.
1. Making implementation changes to implement the new syntax.
1. Spreading the word that the new syntax is now the way to go.
1. Moving over the corpus of demos to the new syntax.
1. If both syntaxes were valid for a period of time, remove the old syntax once it's no longer used.

**Comment by Cypher1** [comment]
Hoping to document my current thoughts in the interests of openness and clear communication.

I'm working on a document to make this more clear, but hopefully providing some short explanations will be enough to aid the writing of documentation (until the syntax council signs off).


**Particle Connections**
Particle Connection syntax will be the same for all handles (including slandles) as you mentioned, with minor changes. The primary difference remaining will be the use of different capabilities and types. We should eventually define these capabilities more cleanly to get down to some kind of basis.

Examples:
Handle: `in Thing {Text value} thing`
Slot typed consume handle: `consumes Slot root`. 
Set Slot typed provide handle with Slot fields: `provides [Slot {formFactor: large}] items`

I plan to unify the Slot fields with other type parameters but as other types do not currently have value parameters the path for unification is not entirely clear.

**Recipe Particle Connections**
My current plan for Recipe connections is to adopt your suggestion (and use the same `consumes` and `provides` from the current plan for particles for consistency). I think this may suggest that `reads` and `writes` may be more appropriate than `in` and `out`. My hope for this is to make verbiage clear, rather than trying to 'noun' all our capabilities (we avoid having an 'in handle connection' and instead have a particle that 'reads a handle connection'.

```
recipe Foo
  use 'rootslotid-root' root
  use username
  particle Bar
    barRoot consumes root
    username reads username
```

I am concerned that this seems to be the reverse of your suggestion (i.e. it is `localName capability connectionName`. I am toying with `localName: capability connectionName` to make the split clearer and ask around for feedback for this.


**Recipe Handle declaration**
Currently we need to use the '`slot' fate for slandles. This is a technical limitation that I hope to remedy.
I'd like to read your one pager, but currently believe that slots should either by 'use'd or 'create'd (i.e. consuming is using a slot that already exists, providing is creating new slots. Mapping should still be valid, but would imply that the mapping particle cannot use the slot in rendering (a restriction that would  not be able to be enforced until slandlesv2).

Syntax:
`map/create/copy/slot 'optional-id' as recipeName`

I plan to update this as I gather feedback and make patches.
Thank you for your execution notes, they'll be a helpful check list.

**Comment by piotrswigon** [comment]
Thank you Josh for outlining your thinking! I'm onboard with 99% of what you wrote. Some minor questions/comments.

1) What are  "value parameters on type"? Can you maybe provide an example. (That's from "I plan to unify the Slot fields with other type parameters but as other types do not currently have value parameters the path for unification is not entirely clear.")
2) I would be strongly supportive of moving from arrows to `reads` / `writes` for the sake of unification with `consumes` / `provides`.  It appears clear the v2 syntax will used reads / writes, so that not a waste of time.
3) I got a bit confused at the end of *Recipe Particle Connections* section. Are you planning to do `particleName reads recipeName` or the other way around? It appears to me that `particleName reads recipeName` is the right order in terms of expressing what is being read.
4) in *Recipe Handle declaration*, I would actually be somewhat satisfied with using `use` for slots, but I think `map` is better - I'll write one is a separate doc as I said. I'm thinking - if a slot is already a slandle and a '\`slot' is a fate, the maybe we could have a `use` or `map` fate and discover whether the type of a slandle is a Slot or an Entity based on what matches the connections of the slandle and what can be found in the context that matches tags and id... Maybe we can talk about this separately.

**Comment by Cypher1** [comment]
1. Value parameters arguments to a type that are not types themselves (e.g. Reference<T> has a type parameter, T, because it is a type function / generic type / polymorphic type [choose your language background + wording]). I use this term because the modality and formFactor arguments to the slot type are not being modeled as types themselves. We could probably treat them as types though, as they're not used by particles at runtime... I think this is an open question, not addressed by the Slots as types doc.

2. Glad you're supportive of the reads writes terminology. I hope we can use this too. Still thinking through the slandles versions, I plan on continuing to use consumes and provides for now but work towards a more expressive system with fewer keywords.

3. Yes, `particleName: reads recipeName` is the current proposal.

4. Totally agree. I hope to remove the current slandle implementation's dependence on the slot fate and only use type + fate + directions to detect slandles.

Thanks for the input. I'm trying to keep the proposal doc up to date as we discuss things further and as I clarify the plan moving forward.

**Comment by Cypher1** [comment]
Progress report:

I've made changes allowing:
- recipe slots
- recipe handles (still in review)
- recipe particle connections
- particle handle connections
- particle slot connections
to all use a colon notation.

I am still working on test coverage and making each test explicit in which syntax is should use.

There's some outstanding tasks, but I believe these will be smaller than the previous (in a rough priority order):
- updated slot syntax to use a pseudo slot type instead of handle and form-factor child items
- updated interface syntax
- support for new direction names
- support for slots with use and map fates

Once these are done we should be able to use the new syntax (by flipping the flag and changing some parse defaults). Then there's a lot of tests to convert or remove if they have a sibling that is already converted.

There's some further elements that require more testing/tweaking in the new syntax, but that I will leave untouched for now (aside from keeping tests working):
- require/construct
- optional names for handle connections

Then I'd like to work on converting types and schemas to match the updated syntax, though I understand this is likely out of scope (and time).

Will update when I reach the next milestone to coordinate change over with @piotrswigon and @shans.

**Comment by piotrswigon** [comment]
Thanks you @Cypher1 ! :) This is awesome :)

**Comment by Cypher1** [comment]
Update: New Syntax is 'in', but is behind flags (in src/runtimes/flags.ts).

List of merged PRs:

- https://github.com/PolymerLabs/arcs/pull/3793
- https://github.com/PolymerLabs/arcs/pull/3685
- https://github.com/PolymerLabs/arcs/pull/3858
- https://github.com/PolymerLabs/arcs/pull/3854
- https://github.com/PolymerLabs/arcs/pull/3852
- https://github.com/PolymerLabs/arcs/pull/3847
- https://github.com/PolymerLabs/arcs/pull/3846
- https://github.com/PolymerLabs/arcs/pull/3832
- https://github.com/PolymerLabs/arcs/pull/3828
- https://github.com/PolymerLabs/arcs/pull/3818
- https://github.com/PolymerLabs/arcs/pull/3817
- https://github.com/PolymerLabs/arcs/pull/3808
- https://github.com/PolymerLabs/arcs/pull/3793
- https://github.com/PolymerLabs/arcs/pull/3946
- https://github.com/PolymerLabs/arcs/pull/3936
- https://github.com/PolymerLabs/arcs/pull/3930
- https://github.com/PolymerLabs/arcs/pull/3922
- https://github.com/PolymerLabs/arcs/pull/3920
- https://github.com/PolymerLabs/arcs/pull/3868
- https://github.com/PolymerLabs/arcs/pull/3865
- https://github.com/PolymerLabs/arcs/pull/3864

**Comment by Cypher1** [comment]
Merged https://github.com/PolymerLabs/arcs/pull/3962, turning the new syntax on.

Will start porting all existing usages of the old syntax and then switch the new syntax to be the default.

**Comment by Cypher1** [comment]
Currently working on porting tests and artifacts in https://github.com/PolymerLabs/arcs/pull/4096

**Comment by Cypher1** [comment]
Merged #4096 and working on https://github.com/PolymerLabs/arcs/pull/4101

Once #4101 is in, we should be able to use https://github.com/PolymerLabs/arcs/pull/4102 to turn the syntax fulling on (and then deprecate the old syntax).

**Comment by piotrswigon** [comment]
Awesome work Josh!

**Comment by Cypher1** [comment]
Thanks Piotr, just need to wrangle wdio shells.

**Comment by Cypher1** [comment]
Update: Syntax is on by default, now just cleaning up old syntax usage so that we can remove it ensure that the new syntax is what is used internally.

These last three PRs should port all the tested syntax to the new form. Allowing `parseBothSyntaxes` to be turned off (i.e. removing support for the old syntax). 
https://github.com/PolymerLabs/arcs/pull/4140
https://github.com/PolymerLabs/arcs/pull/4141
https://github.com/PolymerLabs/arcs/pull/4128

I'll try to land these today and then flip the flag at the end of the week.

**Comment by Cypher1** [comment]
The outstanding changes have been landed, we're now ready to convert internal manifests and then https://github.com/PolymerLabs/arcs/pull/4142 can be landed, ensuring that we only use the new syntax moving forward.

**Comment by Cypher1** [comment]
There's some continued work, clean up of the old code for syntax unification, fixes for some common issues with the syntax itself etc, but I believe that the remaining problems will be best solved by slandles v2 (i.e. actual slandles) being completed properly along side some tech debt clean up.

I'm planning out how to approach moving to v2, focusing on fixing known bugs with the implementation (id sharing between slots and slandles (as handles) not working, transformation + multiplexing bugs).

**Comment by piotrswigon** [comment]
Should we close this bug and have another one for the next stage? As far as I understand the short term syntax change has been rolled out in the GitHub repo. WDYT?

**Comment by Cypher1** [comment]
I'd be happy to do that. Will update the bugs after breakfast :)
Joshua Pratt | Arcs | jopra@google.com
