### ISSUE TITLE
Kotlin-Wasm Slots/Handles persist after deletion

### ISSUE THREAD

**Issue by SHeimlich** [PolymerLabs/arcs#3990]
Steps to reproduce:

1. Take a Kotlin-Wasm recipe that includes at least one slot or handle
2. Build/Run it
3. Remove all references to the slot or handle
4. Re-run bazel build
5. This error appears (this is the slot version, the handle version is the same, just with "handle" instead of slot):
![image](https://user-images.githubusercontent.com/3030811/68149924-96adee80-fef3-11e9-8ec7-fbaa0d34c334.png)

Things attempted to get out of the error state (that failed):
- Restart computer
- Delete bazel-bin folders
- Clearing web browser cache
- running tools/sigh webpack

**Comment by alxrsngrtn** [comment]
Running the bazel-build after deleting slots (after step 3) doesn't help?

**Comment by SHeimlich** [comment]
Yes, that was in the usual steps, I just forgot to say it. I've also updated the original comment above.

**Comment by sjmiles** [comment]
It seems like the Planner is complaining, which is interesting because most of that work is done on the Recipe structure itself, and doesn't involve the actual implementation (unless it's doing speculative execution).

Some things to check:

Check `web-shell` settings and make sure you aren't using _persistent planner storage_ (open the suggestion box, click the gear-icon, and note what it says under "Planner Storage" [should be `volatile`]).

Try running your recipe using dev-shell.

**Comment by SHeimlich** [comment]
Storage is volatile.

Running the code in a devshell does not cause the error. I then tried to run the same recipe in web shell to double check I was still getting the error, and it appeared. In other words, I get the error in webshell, but not devshell, when running the same code.

**Comment by sjmiles** [comment]
> get the error in webshell, but not devshell

This makes sense if the problem is planner related (no planner in dev-shell).

**Comment by SHeimlich** [comment]
Yes, that's what I mean. Screenshot to ensure we're all on the same page:
![image](https://user-images.githubusercontent.com/3030811/68158874-6d965980-ff05-11e9-9268-6d4645bf3cc3.png)

**Comment by sjmiles** [comment]
Root caused this as #4076
