### ISSUE TITLE
arcs-live is down for ... reasons

### ISSUE THREAD

**Issue by shaper** [PolymerLabs/arcs#4074]
This looks like it could relate to recent changes by @sjmiles 

I'm happy to help look at this but want to get his input first.

```
logs-factory.js:1 Failed to load resource: the server responded with a status of 404 ()
pec-industry.js:1 Failed to load resource: the server responded with a status of 404 ()
loader.js:1 Failed to load resource: the server responded with a status of 404 ()
```

**Comment by sjmiles** [comment]
Afaict, this is some kind of problem with the deployment service. 

The errors are 404s, which is to say, it's attempting to reference files that don't exist. For example, it's trying to locate [`build/platform/logs-factory.js`](https://github.com/PolymerLabs/arcs-live/blob/master/build/platform/logs-factory.js) which doesn't exist in the repo (although [`src/platform/logs-factory.ts`](https://github.com/PolymerLabs/arcs-live/blob/master/src/platform/logs-factory.ts) is there).

Last time I spelunked this, it looked like the travis operation that forms the github request was failing to add some *.js files to the index, but this is a rough hypothesis. 

I'd like to reset arcs-live somehow, but I'm not sure how to do that (e.g. can we just recreate the repo?).

**Comment by sjmiles** [comment]
Issue was two-fold:
- we are using Travis deploy option that uploads only changes (instead of force pushing the entire build), I imagine this is on balance good from resource standpoint, but it can obscure problems.
- the deploy tries to remove `build` from .gitignore so that the build folder is pushed to arcs-live (necessary for being _live_), but the regex and the .gitignore file had diverged and the build folder was not being pushed. Because previous build folder was still there, the failures were not totally obvious.

The .gitignore problem was fixed and arcs-live is back.

I also took arcs-live off of Travis' target list (i.e. it was trying to build/test arcs-live over and over), which should save us some resources.
