### ISSUE TITLE
Setting a Handle does not persisting in a deserialized Arc

### ISSUE THREAD

**Issue by SHeimlich** [PolymerLabs/arcs#4712]
In the new storage stack, when an arc is deserialized, setting a handle before fetching it results in the writes not "sticking." It is believed this is caused by the original and new stores having the same ID.

This was discovered when testing the onCreate method in #4687 The workaround is to fetch, then set the the handle.

As part of this, the TODO in the `onCreate only runs for initialization and not reinstantiation` test should be resolved.

**Comment by galganif** [comment]
Investigated this a bit: the new handle has a different id from the old one, but it sets the new value with an empty version map, those the set operation succeeds but the singleton is now in a dual value state (both the old and the new value are retained).
Since the storage proxy has the more up-to-date version map (at least in this test, it has already synced - but that may not be always true) we can instead use the version map from the proxy on every write operation and only pass the clock for the single actor from the handle down.

**Comment by galganif** [comment]
Should be fixed now.
