### ISSUE TITLE
specify type of affordance in slot

### ISSUE THREAD

**Issue by seefeldb** [PolymerLabs/arcs#72]
Particles can be rendered as different kinds of affordances, e.g. as a "summary" or "link" instead of "full" (?). For example a recommender might expose a _sources_ slot and request _link_|_summary_ affordances, disallowing the entire sources to be rendered inline.

Particles can also transition from one affordance to another, which might involve changing slots. E.g. a linked source might on tapping the link want to render itself as _full_, but do so in _root_ slot it requests at that time (in a large screen, maybe both would be visible at the same time, hence two slots) or just need a larger size and change its affordance to _editor_ (TBD: Can the recommender disallow that? What happens then?).

This should probably be strict matching (i.e. no automatic mapping of labels) and thus a small, slowly growing vocabulary.

**Comment by mmandlis** [comment]
we have a basic support for this: particle spec contains a list of affordances supported by the particle, and strategizer verifies all particles in the recipe support the current affordance.

this is a very naive implementation, but I'll close the issue, and will file more specific ones, once we run into issues. @seefeldb feel free to reopen, if you feel otherwise.
